/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Consumption {
  'gas' : number,
  'electricityNormal' : number,
  'electricityHigh' : number,
}
export interface Costs {
  'gasCostTotal' : number,
  'yearlyPrognosis' : YearlyPrognosis,
  'totalOtherCosts' : number,
  'electricityCostTotal' : number,
}
export interface Entry {
  'month' : number,
  'otherCosts' : number,
  'meterReadings' : MeterReadings,
  'year' : number,
}
export interface GlobalMeterReadings {
  'gas' : number,
  'electricityNormal' : number,
  'electricityHigh' : number,
}
export interface MeterReadings {
  'gas' : number,
  'electricityNormal' : number,
  'electricityHigh' : number,
}
export interface UserProfile { 'name' : string, 'dashboardName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YearlyPrices {
  'gasPricePerM3' : number,
  'year' : bigint,
  'electricityNormal' : number,
  'electricityDal' : number,
}
export interface YearlyPrognosis {
  'estimatedTotalOtherCosts' : number,
  'estimatedTotalGasCost' : number,
  'totalMonthsEntered' : bigint,
  'estimatedTotalElectricityCost' : number,
}
export interface YearlyStartingReadings {
  'meterReadings' : MeterReadings,
  'year' : bigint,
}
export interface YearlyTax {
  'year' : bigint,
  'energyTaxGas' : number,
  'energyTaxElec' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCosts' : ActorMethod<[number, number, number, number], Costs>,
  'calculateMonthlyConsumption' : ActorMethod<
    [number, number],
    [] | [Consumption]
  >,
  'deleteEntry' : ActorMethod<[number, number], undefined>,
  'getAllEntries' : ActorMethod<[], Array<Entry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGlobalMeterReadings' : ActorMethod<[], [] | [GlobalMeterReadings]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYearlyPrices' : ActorMethod<[bigint], [] | [YearlyPrices]>,
  'getYearlyStartingReadings' : ActorMethod<
    [bigint],
    [] | [YearlyStartingReadings]
  >,
  'getYearlyTax' : ActorMethod<[bigint], [] | [YearlyTax]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setGlobalMeterReadings' : ActorMethod<[GlobalMeterReadings], undefined>,
  'setYearlyPrices' : ActorMethod<[bigint, number, number, number], undefined>,
  'setYearlyStartingReadings' : ActorMethod<[bigint, MeterReadings], undefined>,
  'setYearlyTax' : ActorMethod<[bigint, number, number], undefined>,
  'upsertEntry' : ActorMethod<
    [number, number, MeterReadings, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];