/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const YearlyPrognosis = IDL.Record({
  'estimatedTotalOtherCosts' : IDL.Float64,
  'estimatedTotalGasCost' : IDL.Float64,
  'totalMonthsEntered' : IDL.Nat,
  'estimatedTotalElectricityCost' : IDL.Float64,
});
export const Costs = IDL.Record({
  'gasCostTotal' : IDL.Float64,
  'yearlyPrognosis' : YearlyPrognosis,
  'totalOtherCosts' : IDL.Float64,
  'electricityCostTotal' : IDL.Float64,
});
export const Consumption = IDL.Record({
  'gas' : IDL.Float64,
  'electricityNormal' : IDL.Float64,
  'electricityHigh' : IDL.Float64,
});
export const MeterReadings = IDL.Record({
  'gas' : IDL.Float64,
  'electricityNormal' : IDL.Float64,
  'electricityHigh' : IDL.Float64,
});
export const Entry = IDL.Record({
  'month' : IDL.Nat8,
  'otherCosts' : IDL.Float64,
  'meterReadings' : MeterReadings,
  'year' : IDL.Nat16,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'dashboardName' : IDL.Text,
});
export const GlobalMeterReadings = IDL.Record({
  'gas' : IDL.Float64,
  'electricityNormal' : IDL.Float64,
  'electricityHigh' : IDL.Float64,
});
export const YearlyPrices = IDL.Record({
  'gasPricePerM3' : IDL.Float64,
  'year' : IDL.Nat,
  'electricityNormal' : IDL.Float64,
  'electricityDal' : IDL.Float64,
});
export const YearlyStartingReadings = IDL.Record({
  'meterReadings' : MeterReadings,
  'year' : IDL.Nat,
});
export const YearlyTax = IDL.Record({
  'year' : IDL.Nat,
  'energyTaxGas' : IDL.Float64,
  'energyTaxElec' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCosts' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat16],
      [Costs],
      ['query'],
    ),
  'calculateMonthlyConsumption' : IDL.Func(
      [IDL.Nat16, IDL.Nat8],
      [IDL.Opt(Consumption)],
      ['query'],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat8, IDL.Nat16], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGlobalMeterReadings' : IDL.Func(
      [],
      [IDL.Opt(GlobalMeterReadings)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearlyPrices' : IDL.Func([IDL.Nat], [IDL.Opt(YearlyPrices)], ['query']),
  'getYearlyStartingReadings' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(YearlyStartingReadings)],
      ['query'],
    ),
  'getYearlyTax' : IDL.Func([IDL.Nat], [IDL.Opt(YearlyTax)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setGlobalMeterReadings' : IDL.Func([GlobalMeterReadings], [], []),
  'setYearlyPrices' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setYearlyStartingReadings' : IDL.Func([IDL.Nat, MeterReadings], [], []),
  'setYearlyTax' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
  'upsertEntry' : IDL.Func(
      [IDL.Nat8, IDL.Nat16, MeterReadings, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const YearlyPrognosis = IDL.Record({
    'estimatedTotalOtherCosts' : IDL.Float64,
    'estimatedTotalGasCost' : IDL.Float64,
    'totalMonthsEntered' : IDL.Nat,
    'estimatedTotalElectricityCost' : IDL.Float64,
  });
  const Costs = IDL.Record({
    'gasCostTotal' : IDL.Float64,
    'yearlyPrognosis' : YearlyPrognosis,
    'totalOtherCosts' : IDL.Float64,
    'electricityCostTotal' : IDL.Float64,
  });
  const Consumption = IDL.Record({
    'gas' : IDL.Float64,
    'electricityNormal' : IDL.Float64,
    'electricityHigh' : IDL.Float64,
  });
  const MeterReadings = IDL.Record({
    'gas' : IDL.Float64,
    'electricityNormal' : IDL.Float64,
    'electricityHigh' : IDL.Float64,
  });
  const Entry = IDL.Record({
    'month' : IDL.Nat8,
    'otherCosts' : IDL.Float64,
    'meterReadings' : MeterReadings,
    'year' : IDL.Nat16,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'dashboardName' : IDL.Text,
  });
  const GlobalMeterReadings = IDL.Record({
    'gas' : IDL.Float64,
    'electricityNormal' : IDL.Float64,
    'electricityHigh' : IDL.Float64,
  });
  const YearlyPrices = IDL.Record({
    'gasPricePerM3' : IDL.Float64,
    'year' : IDL.Nat,
    'electricityNormal' : IDL.Float64,
    'electricityDal' : IDL.Float64,
  });
  const YearlyStartingReadings = IDL.Record({
    'meterReadings' : MeterReadings,
    'year' : IDL.Nat,
  });
  const YearlyTax = IDL.Record({
    'year' : IDL.Nat,
    'energyTaxGas' : IDL.Float64,
    'energyTaxElec' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCosts' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat16],
        [Costs],
        ['query'],
      ),
    'calculateMonthlyConsumption' : IDL.Func(
        [IDL.Nat16, IDL.Nat8],
        [IDL.Opt(Consumption)],
        ['query'],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat8, IDL.Nat16], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGlobalMeterReadings' : IDL.Func(
        [],
        [IDL.Opt(GlobalMeterReadings)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearlyPrices' : IDL.Func([IDL.Nat], [IDL.Opt(YearlyPrices)], ['query']),
    'getYearlyStartingReadings' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(YearlyStartingReadings)],
        ['query'],
      ),
    'getYearlyTax' : IDL.Func([IDL.Nat], [IDL.Opt(YearlyTax)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setGlobalMeterReadings' : IDL.Func([GlobalMeterReadings], [], []),
    'setYearlyPrices' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setYearlyStartingReadings' : IDL.Func([IDL.Nat, MeterReadings], [], []),
    'setYearlyTax' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Float64], [], []),
    'upsertEntry' : IDL.Func(
        [IDL.Nat8, IDL.Nat16, MeterReadings, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };